
ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*

USER_LIB_PATH = /home/pi/sketchbook/libraries
ARDUINO_LIBS = Adafruit_GFX RGBmatrixPanel Timermaster SPI

BOARD_TAG = mega2560

include /usr/share/arduino/Arduino.mk
